import cv2
img = cv2.imread("C:/Users/Dhruv/Desktop/MT/mark.jpg",0)
print(type(img))
print(img[50][100])
cv2.imshow('Original Image',img)
cv2.waitKey(0)
#img=cv2.imread("C:/Users/Dhruv/Desktop/MT/mark.jpg",0)
img1 = cv2.imread("C:/Users/Dhruv/Desktop/MT/mark.jpg",0)
print(type(img1))
print(img1[50][100])
cv2.imshow('Original Image',img1)
cv2.waitKey(0)
cv2.show('Original Image', img1)
img3  = cv2.imread("C:/Users/Dhruv/Desktop/MT/mark.jpg",0)
print(type(img))
print(img3[50][100])
cv2.imshow('Original Image',img3)
cv2.waitKey(0)
img = cv2.imread("C:/Users/Dhruv/Desktop/MT/mark.jpg", -1)
cv2.imshow('Original image', img3)
